import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'
import { useEffect, useState } from 'react'

import {api} from '@/services/api'

export default function Home() {
  const [scholarships, setScholarships] = useState([])

  useEffect(() => {
    getScholarships()
  }, [])

  const getScholarships = async () => {
    const event = await api.get(`/process`)

    setScholarships(event.data)
  }

  return (
    <>
      <Head>
        <title>UniReadi - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar/>
        <div className={styles.presentationContainer}>
          <div className={styles.boxImg}>
            <img src="https://img.freepik.com/fotos-gratis/grupo-de-estudantes-felizes-por-voltar-a-universidade_23-2148586613.jpg?w=2000" alt="" />
          </div>
          <div className={styles.presentationContent}>
            <h2>Bem vindo a UniReadi,</h2>
            <p>uma universidade de tecnologia de renome internacional, localizada em uma das cidades mais vibrantes e inovadoras do mundo. Contando com um Campus altamente tecnologico e corpo docente extremamente qualificado, nós somos dedicados a preparar os líderes do futuro em campos como engenharia, ciência da computação, programação aplicada e muitos outros.</p>
          </div>

          <div className={styles.mouseImg}>
            <img src="https://www.cinepolis.com.br/promocaomonstruosa/img/scroll-down.gif" alt="" />
          </div>

        </div>

        <div className={styles.scholarshipsContainer}>
          <h1>Processos Seletivos abertos</h1>

          <div className={styles.scholarshipsCards}>

            {scholarships.map((ship: any) => (

              <div className={styles.scholarshipsCard} key={ship.id}>

              <img src="/Uni.png" alt="" />

              <div className={styles.contentCard}>

                <h3>{ship.name}</h3>

                <div className={styles.descriptionCard}>
                  <p>{ship.description}</p>
                </div>

                <div className={styles.dataCard}>

                  <div className={styles.valueDataCard}>
                    <p>{ship.vacancys}</p>
                    <p className={styles.keyDataCard}>Vagas</p>
                  </div>

                  <div className={styles.valueDataCard}>
                    <p>{ship.scholarships}</p>
                    <p className={styles.keyDataCard}>Bolsas</p>
                  </div>

                  <div className={styles.valueDataCard}>
                    <p>{ship.course}</p>
                    <p className={styles.keyDataCard}>Curso</p>
                  </div>

                  <div className={styles.valueDataCardLast}>
                    <p>{ship.beginDate.slice(8,10)}/{ship.beginDate.slice(5,7)} - {ship.endDate.slice(8,10)}/{ship.endDate.slice(5,7)}</p>
                    <p className={styles.keyDataCard}>Periodo</p>
                  </div>

                </div>

              </div>

            </div>
            ))}

          </div>
        </div>
      </main>
    </>
  )
}
