import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>UniReadi - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar/>
        <div className={styles.presentationContainer}>
          <div className={styles.boxImg}>
            <img src="https://img.freepik.com/fotos-gratis/grupo-de-estudantes-felizes-por-voltar-a-universidade_23-2148586613.jpg?w=2000" alt="" />
          </div>
          <div className={styles.presentationContent}>
            <h2>Bem vindo a UniReadi,</h2>
            <p>uma universidade de tecnologia de renome internacional, localizada em uma das cidades mais vibrantes e inovadoras do mundo. Contando com um Campus altamente tecnologico e corpo docente extremamente qualificado, nós somos dedicados a preparar os líderes do futuro em campos como engenharia, ciência da computação, programação aplicada e muitos outros.</p>
          </div>

          <div className={styles.mouseImg}>
            <img src="https://www.cinepolis.com.br/promocaomonstruosa/img/scroll-down.gif" alt="" />
          </div>

        </div>

        <div className={styles.scholarshipsContainer}>
          <h1>Processos Seletivos abertos</h1>

          <div className={styles.scholarshipsCards}>

            <div className={styles.scholarshipsCard}>

              <img src="/Uni.png" alt="" />

              <div className={styles.contentCard}>

                <h3>Monitoria Quimica</h3>

                <div className={styles.descriptionCard}>
                  <p>Processo seletivo sendo feito para monitores da turma de quimica 2 da UniReadi.</p>
                </div>

                <div className={styles.dataCard}>

                  <div className={styles.valueDataCard}>
                    <p>3</p>
                    <p className={styles.keyDataCard}>Vagas</p>
                  </div>

                  <div className={styles.valueDataCard}>
                    <p>2</p>
                    <p className={styles.keyDataCard}>Bolsas</p>
                  </div>

                  <div className={styles.valueDataCard}>
                    <p>Quimica</p>
                    <p className={styles.keyDataCard}>Curso</p>
                  </div>

                  <div className={styles.valueDataCardLast}>
                    <p>10/04 - 10/05</p>
                    <p className={styles.keyDataCard}>Periodo</p>
                  </div>

                </div>

              </div>

            </div>

            

          </div>
        </div>
      </main>
    </>
  )
}
